version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    docker:
      - image: node:12.18.3
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: YANDEX_METRICA_TRACKING_ID=$YANDEX_METRICA_TRACKING_ID
            - run: npm ci
            - run: npm run build
  deploy-prod:
    docker:
      - image: node:12.18.3
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -p $DROPLET_PORT $DROPLET_USER@$DROPLET_IP "YANDEX_METRICA_TRACKING_ID=$YANDEX_METRICA_TRACKING_ID ~/pantheon.fun_deploy.sh"

workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy-prod:
          filters:
            branches:
              only:
                - master
          requires:
            - build
