version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
            - run: npm run build
  deploy-prod:
    docker:
      - image: circleci/node:9.6.1
    steps:
      - checkout
      - run: ssh -p $DROPLET_PORT -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP “~/pantheon.fun_deploy.sh”
workflows:
  build-and-deploy:
    jobs:
      # - build
      - deploy-prod:
          filters:
            branches:
              only:
                - master
          # requires:
          #   - build
